# Generated by Django 4.2.7 on 2025-12-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_technology_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='CheatSheets Hub', max_length=200)),
                ('site_owner', models.CharField(default='Reference from OpenLern', max_length=200)),
                ('site_description', models.TextField(default='The ultimate collection of developer cheat sheets.')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
