# Generated by Django 4.2.7 on 2025-12-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_owner_link',
            field=models.URLField(blank=True, default='https://openlern.com'),
        ),
    ]
